next-version: 1.0.0
assembly-versioning-scheme: MajorMinorPatch
assembly-file-versioning-scheme: MajorMinorPatch

branches:
  main:
    regex: ^main$
    mode: ContinuousDelivery
    increment: Patch
    is-release-branch: true
